version: '3.7'

services:
  apache:
    build: .
    container_name: apache
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html/
    networks:
      - billet

  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=billet.password
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - billet

networks:
  billet:
    name: billet-network